# Generated by Django 2.1.5 on 2019-09-07 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190907_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('indian', 'Indian'), ('oriental', 'Oriental'), ('italian', 'Italian'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.Store'),
        ),
    ]
