# Generated by Django 2.1.5 on 2019-09-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190907_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
