# Generated by Django 2.1.5 on 2019-09-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190907_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
